name: Create VM on Dev Push

on:
  push:
    branches:
      - dev

jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run VM creation script
        run: |
          cd assignment10
          ./create_vm.sh
